---
exp_name: baseline_fasterrcnn # 0417
exp_dir: ../exp/augmentation_grid_search
device: 'gpu' # 'mps' in M1 Mac
seed: None # If you want to reproduce set the seed
model_name: faster_rcnn # NCF, NCF_p
train_resume: False

dataset:
    dir: ./data
    img_size: 512
    num_classes: 34
    val_size: 0.2

train:
    optimizer: Adam
    epoch: 1
    lr: 1.0e-3
    wd: 0.0e-4 # Adam
    momentum: 0.9 # SGD
    batch_size : 32

model:

augmentations:
    HorizontalFlip: 
        p: 0.5
    VerticalFlip: 
        p: 0.5
    RandomRotate90: 
        p: 0.5
    RandomBrightnessContrast: 
        p: 0.2
    GaussNoise: 
        p: 0.2